name: Deploy Angular App

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Angular app (always build production version)
      - name: Build Angular app
        run: npx ng build --configuration production

      # Step 5: Deploy to prod branch (always)
      - name: Deploy to prod branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # Checkout the prod branch (create it if it doesn't exist)
          git checkout prod || git checkout --orphan prod

          # Clean up the prod branch (remove all files except .git)
          git rm -rf . || echo "No files to remove"

          # Check the contents of dist/gestion-etc directory to ensure build files exist
          echo "Checking contents of dist/gestion-etc:"
          ls -la dist/gestion-etc/

          # Copy the build files to the root of the prod branch
          cp -r dist/gestion-etc/* .  # Ensure this is the correct path

          # Stage and commit all changes
          git add .
          git commit -m "Deploy production build" || echo "No changes to commit"

          # Force push to prod branch
          git push --force origin prod
