name: Deploy Angular App

on:
  push:
    branches:
      - main
      - prod
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Deploy to prod branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git fetch origin

          if git show-ref --verify --quiet refs/heads/prod; then
            git checkout prod
          else
            git checkout --orphan prod
          fi

          git rm -rf . || echo "No files to remove"

          # Copy only the build files to the root of the prod branch
          cp -r dist/gestion-etc/* .

          # Stage and commit all changes
          git add .
          git commit -m "Deploy production build" || echo "No changes to commit"

          # Force push to prod branch
          git push --force origin prod

          git status
