name: Deploy Angular App

on:
  push:
    branches:
      - main
      - prod
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            npx ng build --configuration production  # Build production version
          fi

      # Deploy to prod branch
      - name: Deploy to prod branch
        if: github.ref == 'refs/heads/prod'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git checkout prod || git checkout --orphan prod

          git rm -rf . || echo "No files to remove"

          echo "Checking dist folder contents:"
          ls dist/gestion-etc/

          cp -r dist/gestion-etc/* .  

          git status
          git add .
          git commit -m "Deploy production build" || echo "No changes to commit"
          git push --force origin prod
